name = "me-builder-worker"
main = "src/index.ts"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[queues.consumers]]
queue = "me-builder-webhook-queue-local"

[vars]
ENVIRONMENT = "local"

[env.local]
name = "me-builder-worker-local"

[[env.local.queues.consumers]]
queue = "me-builder-webhook-queue-local"

[env.local.vars]
ENVIRONMENT = "local"

[env.preview]
name = "me-builder-worker-preview"

[[env.preview.queues.consumers]]
queue = "me-builder-webhook-queue-preview"

[env.preview.vars]
ENVIRONMENT = "preview"

[env.production]
name = "me-builder-worker-production"

[[env.production.queues.consumers]]
queue = "me-builder-webhook-queue-production"

[env.production.vars]
ENVIRONMENT = "production"
