name = "me-builder-web"
pages_build_output_dir = "./dist"
compatibility_date = "2024-07-01"

[vars]
ENVIRONMENT = "local"

[env.local]
name = "me-builder-web-local"

[env.local.vars]
ENVIRONMENT = "local"

[env.preview]
name = "me-builder-web-preview"

[env.preview.vars]
ENVIRONMENT = "preview"

[env.production]
name = "me-builder-web-production"

[env.production.vars]
ENVIRONMENT = "production"
