/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=preview --include-runtime=false --env-interface=WorkerBindings src/worker-configuration.d.ts` (hash: b606938ba9c0bd09ed55cd0cc51fb3d1)
interface __BaseEnv_WorkerBindings {
	AVATAR_BUCKET: R2Bucket;
	PHOTO_DIARY_BUCKET: R2Bucket;
	DB: D1Database;
	BRAIN_VECTOR_INDEX: VectorizeIndex;
	CHAT_TURN_QUEUE: Queue;
	PHOTO_DIARY_DELETION_QUEUE: Queue;
	BRAIN_CHECKPOINT_QUEUE: Queue;
	PROFILE_SUMMARY_QUEUE: Queue;
	BRAIN_VECTOR_QUEUE: Queue;
	DAILY_PROMPT_QUEUE: Queue;
	IMAGES: ImagesBinding;
	ENVIRONMENT: "preview";
	AVATAR_CLEANUP_MODE: "dry-run";
	PHOTO_DIARY_STORAGE_ENABLED: "false";
	CONVERSATION_COORDINATOR: DurableObjectNamespace<import("./index").ConversationCoordinator>;
	ACCOUNT_DATA: DurableObjectNamespace<import("./index").AccountData>;
	COMPATIBILITY_DATA: DurableObjectNamespace<import("./index").CompatibilityData>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "ConversationCoordinator" | "AccountData" | "CompatibilityData";
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "AVATAR_CLEANUP_MODE" | "PHOTO_DIARY_STORAGE_ENABLED">> {}
}
declare module "*.sql" {
	const value: string;
	export default value;
}