/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=preview --include-runtime=false --env-interface=WorkerBindings src/worker-configuration.d.ts` (hash: 2e1e9cfb91704c3b288cc53f662909bc)
interface __BaseEnv_WorkerBindings {
	DB: D1Database;
	CHAT_TURN_QUEUE: Queue;
	ENVIRONMENT: "preview";
	CONVERSATION_COORDINATOR: DurableObjectNamespace<import("./index").ConversationCoordinator>;
	ACCOUNT_DATA: DurableObjectNamespace<import("./index").AccountData>;
	COMPATIBILITY_DATA: DurableObjectNamespace<import("./index").CompatibilityData>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "ConversationCoordinator" | "AccountData" | "CompatibilityData";
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT">> {}
}
declare module "*.sql" {
	const value: string;
	export default value;
}