import type { InfrastructureManifest } from "./manifest";

const header = "# Generated by infra/scripts/generate-wrangler.ts. Do not edit manually.";

function d1(database: InfrastructureManifest["database"], prefix = "") {
  return `[[${prefix}d1_databases]]\nbinding = "DB"\ndatabase_name = "${database.name}"\ndatabase_id = "${database.id}"`;
}

function vectorize(environment: string, prefix = "") {
  return `[[${prefix}vectorize]]\nbinding = "BRAIN_VECTOR_INDEX"\nindex_name = "me-builder-brain-${environment}"`;
}

function queueConsumer(prefix: string, queue: string, deadLetterQueue: string, retries: number) {
  return `[[${prefix}queues.consumers]]\nqueue = "${queue}"\ndead_letter_queue = "${deadLetterQueue}"\nmax_retries = ${retries}`;
}

function queueProducer(prefix: string, queue: string, binding: string) {
  return `[[${prefix}queues.producers]]\nqueue = "${queue}"\nbinding = "${binding}"`;
}

function durableObject(prefix: string, name: string, scriptName?: string) {
  const script = scriptName ? `\nscript_name = "${scriptName}"` : "";
  return `[[${prefix}durable_objects.bindings]]\nname = "${name}"\nclass_name = "${name
    .toLowerCase()
    .replace(/(^|_)([a-z])/g, (_, _separator, letter: string) => letter.toUpperCase())}"${script}`;
}

function r2(bucket: InfrastructureManifest["avatarBucket"], prefix = "") {
  return `[[${prefix}r2_buckets]]\nbinding = "AVATAR_BUCKET"\nbucket_name = "${bucket.name}"`;
}

function kv(namespace: NonNullable<InfrastructureManifest["sessionStore"]>, prefix = "") {
  return `[[${prefix}kv_namespaces]]\nbinding = "SESSION_STORE"\nid = "${namespace.id}"`;
}

function webErrorRateLimit(prefix: string, namespaceId: string) {
  return `[[${prefix}ratelimits]]\nname = "WEB_ERROR_RATE_LIMITER"\nnamespace_id = "${namespaceId}"\n\n[${prefix}ratelimits.simple]\nlimit = 300\nperiod = 60`;
}

function mcpRateLimit(prefix: string, namespaceId: string) {
  return `[[${prefix}ratelimits]]\nname = "MCP_RATE_LIMITER"\nnamespace_id = "${namespaceId}"\n\n[${prefix}ratelimits.simple]\nlimit = 60\nperiod = 60`;
}

function webVars(baseDomain: string, environment: string) {
  return [
    `ENVIRONMENT = "${environment}"`,
    `BASE_DOMAIN = "${baseDomain}"`,
    `WEB_ORIGIN = "https://${baseDomain}"`,
  ];
}

function apiVars(baseDomain: string, environment: string) {
  return [
    ...webVars(baseDomain, environment),
    'SSO_ROLLOUT_MODE = "disabled"',
    'SSO_ROLLOUT_PERCENT = "0"',
    `MCP_RESOURCE_URL = "https://mcp.${baseDomain}/mcp"`,
    'MCP_FEATURE_ENABLED = "false"',
  ];
}

function workerEnvironment(manifest: InfrastructureManifest) {
  const env = manifest.environment;
  const q = manifest.queues;
  const prefix = `env.${env}.`;
  return [
    `[env.${env}]`,
    `name = "me-builder-worker-${env}"`,
    "",
    `[env.${env}.triggers]`,
    'crons = ["0 9,11,12 * * *"]',
    "",
    queueConsumer(prefix, q.webhook.name, q.webhookDeadLetter.name, 3),
    "",
    queueConsumer(prefix, q.billing.name, q.billingDeadLetter.name, 5),
    "",
    queueConsumer(prefix, q.chatTurn.name, q.chatTurnDeadLetter.name, 5),
    "",
    queueConsumer(prefix, q.brainCheckpoint.name, q.brainCheckpointDeadLetter.name, 5),
    "",
    queueConsumer(prefix, q.profileSummary.name, q.profileSummaryDeadLetter.name, 5),
    "",
    queueConsumer(prefix, q.brainVector.name, q.brainVectorDeadLetter.name, 5),
    "",
    queueConsumer(prefix, q.dailyPrompt.name, q.dailyPromptDeadLetter.name, 5),
    "",
    queueProducer(prefix, q.chatTurn.name, "CHAT_TURN_QUEUE"),
    "",
    queueProducer(prefix, q.brainCheckpoint.name, "BRAIN_CHECKPOINT_QUEUE"),
    "",
    queueProducer(prefix, q.profileSummary.name, "PROFILE_SUMMARY_QUEUE"),
    "",
    queueProducer(prefix, q.brainVector.name, "BRAIN_VECTOR_QUEUE"),
    "",
    queueProducer(prefix, q.dailyPrompt.name, "DAILY_PROMPT_QUEUE"),
    "",
    durableObject(prefix, "CONVERSATION_COORDINATOR"),
    "",
    durableObject(prefix, "ACCOUNT_DATA"),
    "",
    durableObject(prefix, "COMPATIBILITY_DATA"),
    "",
    d1(manifest.database, prefix),
    "",
    r2(manifest.avatarBucket, prefix),
    "",
    vectorize(env, prefix),
    "",
    `[env.${env}.vars]`,
    `ENVIRONMENT = "${env}"`,
    'AVATAR_CLEANUP_MODE = "dry-run"',
  ].join("\n");
}

function apiEnvironment(manifest: InfrastructureManifest) {
  const env = manifest.environment;
  const host = `api.${manifest.baseDomain}`;
  const prefix = `env.${env}.`;
  const config = [
    `[env.${env}]`,
    `name = "me-builder-api-${env}"`,
    "routes = [",
    `  { pattern = "${host}", custom_domain = true }`,
    "]",
    "",
    queueProducer(prefix, manifest.queues.webhook.name, "WEBHOOK_QUEUE"),
    "",
    queueProducer(prefix, manifest.queues.billing.name, "BILLING_QUEUE"),
    "",
    queueProducer(prefix, manifest.queues.profileSummary.name, "PROFILE_SUMMARY_QUEUE"),
    "",
    webErrorRateLimit(prefix, env === "preview" ? "11002" : "11003"),
    "",
    d1(manifest.database, prefix),
  ];
  if (manifest.sessionStore) config.push("", kv(manifest.sessionStore, prefix));
  if (env !== "production") config.push("", vectorize(env, prefix));
  config.push(
    "",
    r2(manifest.avatarBucket, prefix),
    "",
    durableObject(prefix, "ACCOUNT_DATA", `me-builder-worker-${env}`),
    "",
    durableObject(prefix, "CONVERSATION_COORDINATOR", `me-builder-worker-${env}`),
    "",
    durableObject(prefix, "COMPATIBILITY_DATA", `me-builder-worker-${env}`),
    "",
    `[env.${env}.vars]`,
    ...apiVars(manifest.baseDomain, env),
  );
  return config.join("\n");
}

function mcpEnvironment(manifest: InfrastructureManifest) {
  const env = manifest.environment;
  const host = `mcp.${manifest.baseDomain}`;
  const prefix = `env.${env}.`;
  return `[env.${env}]\nname = "me-builder-mcp-${env}"\nroutes = [\n  { pattern = "${host}", custom_domain = true }\n]\n\n${d1(manifest.database, prefix)}\n\n${vectorize(env, prefix)}\n\n${durableObject(prefix, "ACCOUNT_DATA", `me-builder-worker-${env}`)}\n\n${mcpRateLimit(prefix, env === "preview" ? "12002" : "12003")}\n\n[env.${env}.vars]\n${webVars(manifest.baseDomain, env).join("\n")}\nMCP_FEATURE_ENABLED = "false"`;
}

export function renderWranglerConfigs(
  preview: InfrastructureManifest,
  production: InfrastructureManifest,
) {
  const localDatabase = { id: "me-builder-db-local-id", name: "me-builder-db-local" };
  const localQueues = {
    webhook: { id: "local", name: "me-builder-webhook-queue-local" },
    webhookDeadLetter: { id: "local", name: "me-builder-webhook-dlq-local" },
    billing: { id: "local", name: "me-builder-billing-queue-local" },
    billingDeadLetter: { id: "local", name: "me-builder-billing-dlq-local" },
    chatTurn: { id: "local", name: "me-builder-chat-turn-queue-local" },
    chatTurnDeadLetter: { id: "local", name: "me-builder-chat-turn-dlq-local" },
    brainCheckpoint: { id: "local", name: "me-builder-brain-checkpoint-queue-local" },
    brainCheckpointDeadLetter: { id: "local", name: "me-builder-brain-checkpoint-dlq-local" },
    profileSummary: { id: "local", name: "me-builder-profile-summary-queue-local" },
    profileSummaryDeadLetter: { id: "local", name: "me-builder-profile-summary-dlq-local" },
    brainVector: { id: "local", name: "me-builder-brain-vector-queue-local" },
    brainVectorDeadLetter: { id: "local", name: "me-builder-brain-vector-dlq-local" },
    dailyPrompt: { id: "local", name: "me-builder-daily-prompt-queue-local" },
    dailyPromptDeadLetter: { id: "local", name: "me-builder-daily-prompt-dlq-local" },
  };
  const localManifest = {
    ...preview,
    environment: "local" as never,
    baseDomain: "localhost",
    database: localDatabase,
    avatarBucket: { name: "me-builder-avatar-local" },
    sessionStore: { id: "me-builder-session-local-id", name: "me-builder-session-local" },
    queues: localQueues,
  };
  const worker = [
    header,
    'name = "me-builder-worker"',
    'main = "src/index.ts"',
    'compatibility_date = "2026-08-06"',
    'compatibility_flags = ["nodejs_compat"]',
    "",
    "[observability]",
    "enabled = true",
    "",
    "[observability.logs]",
    "invocation_logs = false",
    "",
    "[triggers]",
    'crons = ["0 9,11,12 * * *"]',
    "",
    queueConsumer("", localQueues.webhook.name, localQueues.webhookDeadLetter.name, 3),
    "",
    queueConsumer("", localQueues.billing.name, localQueues.billingDeadLetter.name, 5),
    "",
    queueConsumer("", localQueues.chatTurn.name, localQueues.chatTurnDeadLetter.name, 5),
    "",
    queueConsumer(
      "",
      localQueues.brainCheckpoint.name,
      localQueues.brainCheckpointDeadLetter.name,
      5,
    ),
    "",
    queueConsumer(
      "",
      localQueues.profileSummary.name,
      localQueues.profileSummaryDeadLetter.name,
      5,
    ),
    "",
    queueConsumer("", localQueues.brainVector.name, localQueues.brainVectorDeadLetter.name, 5),
    "",
    queueConsumer("", localQueues.dailyPrompt.name, localQueues.dailyPromptDeadLetter.name, 5),
    "",
    queueProducer("", localQueues.chatTurn.name, "CHAT_TURN_QUEUE"),
    "",
    queueProducer("", localQueues.brainCheckpoint.name, "BRAIN_CHECKPOINT_QUEUE"),
    "",
    queueProducer("", localQueues.profileSummary.name, "PROFILE_SUMMARY_QUEUE"),
    "",
    queueProducer("", localQueues.brainVector.name, "BRAIN_VECTOR_QUEUE"),
    "",
    queueProducer("", localQueues.dailyPrompt.name, "DAILY_PROMPT_QUEUE"),
    "",
    durableObject("", "CONVERSATION_COORDINATOR"),
    "",
    durableObject("", "ACCOUNT_DATA"),
    "",
    durableObject("", "COMPATIBILITY_DATA"),
    "",
    "[[migrations]]",
    'tag = "v1"',
    'new_sqlite_classes = ["ConversationCoordinator"]',
    "",
    "[[migrations]]",
    'tag = "v2"',
    'new_sqlite_classes = ["AccountData"]',
    "",
    "[[migrations]]",
    'tag = "v3"',
    'new_sqlite_classes = ["CompatibilityData"]',
    "",
    "[[rules]]",
    'type = "Text"',
    'globs = ["**/*.sql"]',
    "fallthrough = true",
    "",
    d1(localDatabase),
    "",
    r2(localManifest.avatarBucket),
    "",
    vectorize("local"),
    "",
    "[vars]",
    'ENVIRONMENT = "local"',
    'AVATAR_CLEANUP_MODE = "dry-run"',
    "",
    workerEnvironment(localManifest),
    "",
    workerEnvironment(preview),
    "",
    workerEnvironment(production),
    "",
  ].join("\n");

  const apiLocal = [
    "[env.local]",
    'name = "me-builder-api-local"',
    "",
    queueProducer("env.local.", localQueues.webhook.name, "WEBHOOK_QUEUE"),
    "",
    queueProducer("env.local.", localQueues.billing.name, "BILLING_QUEUE"),
    "",
    queueProducer("env.local.", localQueues.profileSummary.name, "PROFILE_SUMMARY_QUEUE"),
    "",
    webErrorRateLimit("env.local.", "11001"),
    "",
    d1(localDatabase, "env.local."),
    "",
    kv(localManifest.sessionStore, "env.local."),
    "",
    vectorize("local", "env.local."),
    "",
    r2(localManifest.avatarBucket, "env.local."),
    "",
    durableObject("env.local.", "ACCOUNT_DATA", "me-builder-worker-local"),
    "",
    durableObject("env.local.", "CONVERSATION_COORDINATOR", "me-builder-worker-local"),
    "",
    durableObject("env.local.", "COMPATIBILITY_DATA", "me-builder-worker-local"),
    "",
    "[env.local.vars]",
    'ENVIRONMENT = "local"',
    'WEB_ORIGIN = "http://localhost:5173"',
    'SSO_ROLLOUT_MODE = "disabled"',
    'SSO_ROLLOUT_PERCENT = "0"',
  ].join("\n");
  const api = [
    header,
    'name = "me-builder-api"',
    'main = "src/index.ts"',
    'compatibility_date = "2026-07-29"',
    'compatibility_flags = ["nodejs_compat"]',
    "",
    "[observability]",
    "enabled = true",
    "",
    "[observability.logs]",
    "invocation_logs = false",
    "",
    queueProducer("", localQueues.webhook.name, "WEBHOOK_QUEUE"),
    "",
    queueProducer("", localQueues.billing.name, "BILLING_QUEUE"),
    "",
    queueProducer("", localQueues.profileSummary.name, "PROFILE_SUMMARY_QUEUE"),
    "",
    webErrorRateLimit("", "11001"),
    "",
    d1(localDatabase),
    "",
    kv(localManifest.sessionStore),
    "",
    vectorize("local"),
    "",
    r2(localManifest.avatarBucket),
    "",
    durableObject("", "ACCOUNT_DATA", "me-builder-worker-local"),
    "",
    durableObject("", "CONVERSATION_COORDINATOR", "me-builder-worker-local"),
    "",
    durableObject("", "COMPATIBILITY_DATA", "me-builder-worker-local"),
    "",
    "[vars]",
    'ENVIRONMENT = "local"',
    'WEB_ORIGIN = "http://localhost:5173"',
    'SSO_ROLLOUT_MODE = "disabled"',
    'SSO_ROLLOUT_PERCENT = "0"',
    "",
    apiLocal,
    "",
    apiEnvironment(preview),
    "",
    apiEnvironment(production),
    "",
  ].join("\n");

  const mcp = `${header}\nname = "me-builder-mcp"\nmain = "src/index.ts"\ncompatibility_date = "2026-07-29"\ncompatibility_flags = ["nodejs_compat"]\n\n[observability]\nenabled = true\n\n${d1(localDatabase)}\n\n${vectorize("local")}\n\n${durableObject("", "ACCOUNT_DATA", "me-builder-worker-local")}\n\n${mcpRateLimit("", "12001")}\n\n[vars]\nENVIRONMENT = "local"\nWEB_ORIGIN = "http://localhost:5173"\nBASE_URL = "http://localhost:3001"\nAPI_URL = "http://localhost:3000"\nMCP_FEATURE_ENABLED = "false"\n\n[env.local]\nname = "me-builder-mcp-local"\n\n${d1(localDatabase, "env.local.")}\n\n${vectorize("local", "env.local.")}\n\n${durableObject("env.local.", "ACCOUNT_DATA", "me-builder-worker-local")}\n\n${mcpRateLimit("env.local.", "12001")}\n\n[env.local.vars]\nENVIRONMENT = "local"\nWEB_ORIGIN = "http://localhost:5173"\nBASE_URL = "http://localhost:3001"\nAPI_URL = "http://localhost:3000"\nMCP_FEATURE_ENABLED = "false"\n\n${mcpEnvironment(preview)}\n\n${mcpEnvironment(production)}\n`;

  const lib = `${header}\nname = "me-builder-lib"\n\n${d1(localDatabase)}\nmigrations_dir = "drizzle"\n\n[env.preview]\n${d1(preview.database, "env.preview.")}\nmigrations_dir = "drizzle"\n\n[env.production]\n${d1(production.database, "env.production.")}\nmigrations_dir = "drizzle"\n`;
  return { worker, api, mcp, lib };
}
