import type { InfrastructureManifest } from "./manifest";

const header = "# Generated by infra/scripts/generate-wrangler.ts. Do not edit manually.";

function d1(database: InfrastructureManifest["database"], prefix = "") {
  return `[[${prefix}d1_databases]]\nbinding = "DB"\ndatabase_name = "${database.name}"\ndatabase_id = "${database.id}"`;
}

function workerEnvironment(manifest: InfrastructureManifest) {
  const env = manifest.environment;
  const q = manifest.queues;
  return `[env.${env}]\nname = "me-builder-worker-${env}"\n\n[[env.${env}.queues.consumers]]\nqueue = "${q.webhook.name}"\ndead_letter_queue = "${q.webhookDeadLetter.name}"\nmax_retries = 3\n\n[[env.${env}.queues.consumers]]\nqueue = "${q.chatTurn.name}"\ndead_letter_queue = "${q.chatTurnDeadLetter.name}"\nmax_retries = 5\n\n[[env.${env}.queues.consumers]]\nqueue = "${q.brainCheckpoint.name}"\ndead_letter_queue = "${q.brainCheckpointDeadLetter.name}"\nmax_retries = 5\n\n[[env.${env}.queues.producers]]\nqueue = "${q.chatTurn.name}"\nbinding = "CHAT_TURN_QUEUE"\n\n[[env.${env}.queues.producers]]\nqueue = "${q.brainCheckpoint.name}"\nbinding = "BRAIN_CHECKPOINT_QUEUE"\n\n[[env.${env}.durable_objects.bindings]]\nname = "CONVERSATION_COORDINATOR"\nclass_name = "ConversationCoordinator"\n\n[[env.${env}.durable_objects.bindings]]\nname = "ACCOUNT_DATA"\nclass_name = "AccountData"\n\n[[env.${env}.durable_objects.bindings]]\nname = "COMPATIBILITY_DATA"\nclass_name = "CompatibilityData"\n\n${d1(manifest.database, `env.${env}.`)}\n\n[env.${env}.vars]\nENVIRONMENT = "${env}"`;
}

function apiEnvironment(manifest: InfrastructureManifest) {
  const env = manifest.environment;
  const host = env === "preview" ? "api.stg.kagami.kyosuke.dev" : "api.kagami.kyosuke.dev";
  return `[env.${env}]\nname = "me-builder-api-${env}"\nroutes = [\n  { pattern = "${host}", custom_domain = true }\n]\n\n[[env.${env}.queues.producers]]\nqueue = "${manifest.queues.webhook.name}"\nbinding = "WEBHOOK_QUEUE"\n\n${d1(manifest.database, `env.${env}.`)}\n\n[[env.${env}.durable_objects.bindings]]\nname = "ACCOUNT_DATA"\nclass_name = "AccountData"\nscript_name = "me-builder-worker-${env}"\n\n[[env.${env}.durable_objects.bindings]]\nname = "COMPATIBILITY_DATA"\nclass_name = "CompatibilityData"\nscript_name = "me-builder-worker-${env}"\n\n[env.${env}.vars]\nENVIRONMENT = "${env}"`;
}

function mcpEnvironment(manifest: InfrastructureManifest) {
  const env = manifest.environment;
  const host = env === "preview" ? "mcp.stg.kagami.kyosuke.dev" : "mcp.kagami.kyosuke.dev";
  return `[env.${env}]\nname = "me-builder-mcp-${env}"\nroutes = [\n  { pattern = "${host}", custom_domain = true }\n]\n\n${d1(manifest.database, `env.${env}.`)}\n\n[env.${env}.vars]\nENVIRONMENT = "${env}"`;
}

export function renderWranglerConfigs(
  preview: InfrastructureManifest,
  production: InfrastructureManifest,
) {
  const localDatabase = { id: "me-builder-db-local-id", name: "me-builder-db-local" };
  const localQueues = {
    webhook: { id: "local", name: "me-builder-webhook-queue-local" },
    webhookDeadLetter: { id: "local", name: "me-builder-webhook-dlq-local" },
    chatTurn: { id: "local", name: "me-builder-chat-turn-queue-local" },
    chatTurnDeadLetter: { id: "local", name: "me-builder-chat-turn-dlq-local" },
    brainCheckpoint: { id: "local", name: "me-builder-brain-checkpoint-queue-local" },
    brainCheckpointDeadLetter: { id: "local", name: "me-builder-brain-checkpoint-dlq-local" },
  };
  const localManifest = {
    ...preview,
    environment: "local" as never,
    database: localDatabase,
    queues: localQueues,
  };
  const worker = `${header}\nname = "me-builder-worker"\nmain = "src/index.ts"\ncompatibility_date = "2026-08-06"\ncompatibility_flags = ["nodejs_compat"]\n\n[observability]\nenabled = true\n\n[observability.logs]\ninvocation_logs = false\n\n[[queues.consumers]]\nqueue = "me-builder-webhook-queue-local"\ndead_letter_queue = "me-builder-webhook-dlq-local"\nmax_retries = 3\n\n[[queues.consumers]]\nqueue = "me-builder-chat-turn-queue-local"\ndead_letter_queue = "me-builder-chat-turn-dlq-local"\nmax_retries = 5\n\n[[queues.consumers]]\nqueue = "me-builder-brain-checkpoint-queue-local"\ndead_letter_queue = "me-builder-brain-checkpoint-dlq-local"\nmax_retries = 5\n\n[[queues.producers]]\nqueue = "me-builder-chat-turn-queue-local"\nbinding = "CHAT_TURN_QUEUE"\n\n[[queues.producers]]\nqueue = "me-builder-brain-checkpoint-queue-local"\nbinding = "BRAIN_CHECKPOINT_QUEUE"\n\n[[durable_objects.bindings]]\nname = "CONVERSATION_COORDINATOR"\nclass_name = "ConversationCoordinator"\n\n[[durable_objects.bindings]]\nname = "ACCOUNT_DATA"\nclass_name = "AccountData"\n\n[[durable_objects.bindings]]\nname = "COMPATIBILITY_DATA"\nclass_name = "CompatibilityData"\n\n[[migrations]]\ntag = "v1"\nnew_sqlite_classes = ["ConversationCoordinator"]\n\n[[migrations]]\ntag = "v2"\nnew_sqlite_classes = ["AccountData"]\n\n[[migrations]]\ntag = "v3"\nnew_sqlite_classes = ["CompatibilityData"]\n\n[[rules]]\ntype = "Text"\nglobs = ["**/*.sql"]\nfallthrough = true\n\n${d1(localDatabase)}\n\n[vars]\nENVIRONMENT = "local"\n\n${workerEnvironment(localManifest)}\n\n${workerEnvironment(preview)}\n\n${workerEnvironment(production)}\n`;

  const apiLocal = `[env.local]\nname = "me-builder-api-local"\n\n[[env.local.queues.producers]]\nqueue = "me-builder-webhook-queue-local"\nbinding = "WEBHOOK_QUEUE"\n\n${d1(localDatabase, "env.local.")}\n\n[[env.local.durable_objects.bindings]]\nname = "ACCOUNT_DATA"\nclass_name = "AccountData"\nscript_name = "me-builder-worker-local"\n\n[[env.local.durable_objects.bindings]]\nname = "COMPATIBILITY_DATA"\nclass_name = "CompatibilityData"\nscript_name = "me-builder-worker-local"\n\n[env.local.vars]\nENVIRONMENT = "local"`;
  const api = `${header}\nname = "me-builder-api"\nmain = "src/index.ts"\ncompatibility_date = "2026-07-29"\ncompatibility_flags = ["nodejs_compat"]\n\n[observability]\nenabled = true\n\n[observability.logs]\ninvocation_logs = false\n\n[[queues.producers]]\nqueue = "me-builder-webhook-queue-local"\nbinding = "WEBHOOK_QUEUE"\n\n${d1(localDatabase)}\n\n[[durable_objects.bindings]]\nname = "ACCOUNT_DATA"\nclass_name = "AccountData"\nscript_name = "me-builder-worker-local"\n\n[[durable_objects.bindings]]\nname = "COMPATIBILITY_DATA"\nclass_name = "CompatibilityData"\nscript_name = "me-builder-worker-local"\n\n[vars]\nENVIRONMENT = "local"\n\n${apiLocal}\n\n${apiEnvironment(preview)}\n\n${apiEnvironment(production)}\n`;

  const mcp = `${header}\nname = "me-builder-mcp"\nmain = "src/index.ts"\ncompatibility_date = "2024-07-01"\ncompatibility_flags = ["nodejs_compat"]\n\n[observability]\nenabled = true\n\n${d1(localDatabase)}\n\n[vars]\nENVIRONMENT = "local"\n\n[env.local]\nname = "me-builder-mcp-local"\n\n${d1(localDatabase, "env.local.")}\n\n[env.local.vars]\nENVIRONMENT = "local"\n\n${mcpEnvironment(preview)}\n\n${mcpEnvironment(production)}\n`;

  const lib = `${header}\nname = "me-builder-lib"\n\n${d1(localDatabase)}\nmigrations_dir = "drizzle"\n\n[env.preview]\n${d1(preview.database, "env.preview.")}\nmigrations_dir = "drizzle"\n\n[env.production]\n${d1(production.database, "env.production.")}\nmigrations_dir = "drizzle"\n`;
  return { worker, api, mcp, lib };
}
