config:
  me-builder-gcp-platform:environment: development
  me-builder-gcp-platform:budgetCurrencyCode: JPY
  me-builder-gcp-platform:monthlyBudgetAmount: 10000
  me-builder-gcp-platform:identityPlatformActiveCredentialSlot: primary
  me-builder-gcp-platform:identityPlatformCredentialGenerations:
    primary: v1
    secondary: null
