config:
  me-builder-gcp-platform:environment: production
  me-builder-gcp-platform:identityPlatformActiveCredentialSlot: primary
  me-builder-gcp-platform:identityPlatformCredentialGenerations:
    primary: v1
    secondary: null
