/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=preview --include-runtime=false --env-interface=ApiBindings src/worker-configuration.d.ts` (hash: 48cc1b7204c8738b5037ddcd261f078f)
interface __BaseEnv_ApiBindings {
	DB: D1Database;
	BRAIN_VECTOR_INDEX: VectorizeIndex;
	WEBHOOK_QUEUE: Queue;
	ENVIRONMENT: "preview";
	ACCOUNT_DATA: DurableObjectNamespace /* AccountData from me-builder-worker-preview */;
	COMPATIBILITY_DATA: DurableObjectNamespace /* CompatibilityData from me-builder-worker-preview */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_ApiBindings {}
}
interface ApiBindings extends __BaseEnv_ApiBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT">> {}
}
