/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=preview --include-runtime=false --env-interface=ApiBindings src/worker-configuration.d.ts` (hash: 4f67a22a30936a5dbf8007a1d645b678)
interface __BaseEnv_ApiBindings {
	DB: D1Database;
	WEBHOOK_QUEUE: Queue;
	ENVIRONMENT: "preview";
	CONVERSATION_COORDINATOR: DurableObjectNamespace /* ConversationCoordinator from me-builder-worker-preview */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_ApiBindings {}
}
interface ApiBindings extends __BaseEnv_ApiBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT">> {}
}
