/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=preview --include-runtime=false --env-interface=ApiBindings src/worker-configuration.d.ts` (hash: e2a889bb00121ad9a193b5d3fc0a7cd2)
interface __BaseEnv_ApiBindings {
	AVATAR_BUCKET: R2Bucket;
	DB: D1Database;
	BRAIN_VECTOR_INDEX: VectorizeIndex;
	WEBHOOK_QUEUE: Queue;
	BILLING_QUEUE: Queue;
	PROFILE_SUMMARY_QUEUE: Queue;
	WEB_ERROR_RATE_LIMITER: RateLimit;
	ENVIRONMENT: "preview";
	WEB_ORIGIN: "https://stg.kagami.kyosuke.dev";
	SSO_ROLLOUT_MODE: "disabled";
	SSO_ROLLOUT_PERCENT: "0";
	ACCOUNT_DATA: DurableObjectNamespace /* AccountData from me-builder-worker-preview */;
	CONVERSATION_COORDINATOR: DurableObjectNamespace /* ConversationCoordinator from me-builder-worker-preview */;
	COMPATIBILITY_DATA: DurableObjectNamespace /* CompatibilityData from me-builder-worker-preview */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_ApiBindings {}
}
interface ApiBindings extends __BaseEnv_ApiBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "WEB_ORIGIN" | "SSO_ROLLOUT_MODE" | "SSO_ROLLOUT_PERCENT">> {}
}
