/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=preview --include-runtime=false --env-interface=McpBindings src/worker-configuration.d.ts` (hash: 2bceff2f404e997c9c5973c6a3cae2e9)
interface __BaseEnv_McpBindings {
	DB: D1Database;
	BRAIN_VECTOR_INDEX: VectorizeIndex;
	MCP_RATE_LIMITER: RateLimit;
	ENVIRONMENT: "preview";
	BASE_DOMAIN: "stg.kagami.kyosuke.dev";
	WEB_ORIGIN: "https://stg.kagami.kyosuke.dev";
	MCP_FEATURE_ENABLED: "false";
	ACCOUNT_DATA: DurableObjectNamespace /* AccountData from me-builder-worker-preview */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_McpBindings {}
}
interface McpBindings extends __BaseEnv_McpBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "BASE_DOMAIN" | "WEB_ORIGIN" | "MCP_FEATURE_ENABLED">> {}
}
