name = "me-builder-api"
main = "src/index.ts"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "local"

[env.local]
name = "me-builder-api-local"

[env.local.vars]
ENVIRONMENT = "local"

[env.preview]
name = "me-builder-api-preview"
routes = [
  { pattern = "api.stg.kagami.kyosuke.dev", custom_domain = true }
]

[env.preview.vars]
ENVIRONMENT = "preview"

[env.production]
name = "me-builder-api-production"

[env.production.vars]
ENVIRONMENT = "production"
