name = "me-builder-api"
main = "src/index.ts"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[queues.producers]]
queue = "me-builder-webhook-queue-local"
binding = "WEBHOOK_QUEUE"

[[d1_databases]]
binding = "DB"
database_name = "me-builder-db-local"
database_id = "me-builder-db-local-id"

[vars]
ENVIRONMENT = "local"

[env.local]
name = "me-builder-api-local"

[[env.local.queues.producers]]
queue = "me-builder-webhook-queue-local"
binding = "WEBHOOK_QUEUE"

[[env.local.d1_databases]]
binding = "DB"
database_name = "me-builder-db-local"
database_id = "me-builder-db-local-id"

[env.local.vars]
ENVIRONMENT = "local"

[env.preview]
name = "me-builder-api-preview"
routes = [
  { pattern = "api.stg.kagami.kyosuke.dev", custom_domain = true }
]

[[env.preview.queues.producers]]
queue = "me-builder-webhook-queue-preview"
binding = "WEBHOOK_QUEUE"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "me-builder-db-preview"
database_id = "me-builder-db-preview-id"

[env.preview.vars]
ENVIRONMENT = "preview"

[env.production]
name = "me-builder-api-production"
routes = [
  { pattern = "api.kagami.kyosuke.dev", custom_domain = true }
]

[[env.production.queues.producers]]
queue = "me-builder-webhook-queue-production"
binding = "WEBHOOK_QUEUE"

[[env.production.d1_databases]]
binding = "DB"
database_name = "me-builder-db-production"
database_id = "me-builder-db-production-id"

[env.production.vars]
ENVIRONMENT = "production"
